### ISSUE TITLE
Please correct npm maintainers configuration.

### ISSUE THREAD

**Issue by GermanBluefox** [rg-engineering/ioBroker.pvoutputorg#34]
## ioBroker adapter checker for npm access

Access right check for adapter pvoutputorg returned the following issue:

Bluefox was not found in the collaborators on NPM!.
Please execute in adapter directory: "npm owner add bluefox iobroker.pvoutputorg"

Current maintainers are 
    rg-engineering <info@rg-engineering.eu>

Please fix the above error as soon as possible.
All adapters listed at ioBroker repositories must have 'bluefox' added as maintainer.

Future version updates at the repositories will be suspended until this problem is fixed.

**Comment by mcm1957** [comment]
@rg-engineering 

Please fix the npm access rights for this adapter by executing "npm owner add bluefox iobroker.pvoutputorg" in adapter driectory.

If you encounter any problems, please let us know.

@mcm1957

**Comment by rg-engineering** [comment]
@GermanBluefox , @mcm1957 done:
```
E:\Software\ioBroker\ioBroker.pvoutputorg>npm owner add bluefox iobroker.pvoutputorg
npm notice INFO: User bluefox invited to package iobroker.pvoutputorg successfully.
+ bluefox (iobroker.pvoutputorg)
```
